import type { CheckSectionModel } from '@features/sections/check-section/check-section';
import { createCheckSection } from '../../build/section-factories';
import { createBatteryCheckSection, SPEED_CHECK_SECTION } from '../shared.sections';

export const DREHLEITER_UVV_BASE_SECTIONS: CheckSectionModel[] = [
  createCheckSection('sec-dl-1', '1. Fahrerhaus innen', 'dl-1', [
    'Gangsperre',
    'Nebenantrieb-Kontrollleuchte',
    'Kontrollleuchten Achsverriegelung / Sitz / Korb',
    'Kontrollleuchten Fahrerhaus',
    'Warnsummer Grundstellung / Geräteraum',
    'Verriegelung / Notbetätigung PA',
    'Ladeerhaltung',
    'Durchsageanlage',
    'Batteriehauptschalter',
    'RÜckfahrkamerasystem',
    'Lagerung / Sicherung Gegenstände',
    'Beschilderung Masse / Gewichte'
  ]),
  createCheckSection('sec-dl-2', '2. Fahrerhaus aussen', 'dl-2', [
    'Akustische Warneinrichtung',
    'Beleuchtung Chassis / Aufbau',
    'Abdeckkappen Ladeerhaltung',
    'Beschilderung Fahrerhaus',
    'Schäkel (Splint / Beschilderung)'
  ]),
  createCheckSection('sec-dl-3', '3. Fahrzeugaufbau', 'dl-3', [
    'Fahrzeug auf Unfallschäden',
    'Kraftstoffbehälter',
    'Einfüllstutzen',
    'Tankdeckel',
    'Tankklappe',
    'AdBlue-Behälter',
    'Radkeile inkl. Halter und Verriegelung',
    'Ölstand Haupthydraulik'
  ]),
  createBatteryCheckSection('4. Batterien'),
  createCheckSection('sec-dl-5', '5. Gerätekästen', 'dl-5', [
    'Gerätekästen',
    'Überwachungseinrichtung',
    'Beleuchtung',
    'Festigkeit der Anbauteile'
  ]),
  createCheckSection('sec-dl-6', '6. Aufstiege', 'dl-6', ['Aufstiege', 'Aufstiegsleitern']),
  createCheckSection('sec-dl-7', '7. Abstützung', 'dl-7', [
    'Beleuchtungen / Funktionen / Befestigungen / Dichtheit',
    'Abstützung',
    'Abstutzbedienpulte',
    'Hydraulik Unterwagen',
    'Überwachung (Sensorik)',
    'Bodenkontaktmechanik',
    'Abstützbalken / Stützträger',
    'Schweissnähte Abstützträger',
    'Schmierstellen Unterwagen',
    'Wartungsdeckel Abstützträger',
    'Energiezuführungen / Ölharfen',
    'Achsverriegelung'
  ]),
  createCheckSection('sec-dl-8', '8. Notbetriebseinrichtungen', 'dl-8', [
    'Notbetriebseinrichtungen Unterwagen',
    'Notbetriebspumpen / Notbetriebsmotor',
    'Ventile Notbetrieb Abstützung',
    'Umschaltvorrichtung Energiefreigabe Korbmotoren',
    'Umschaltventil Unterwagen / Oberwagen'
  ]),
  createCheckSection('sec-dl-9', '9. Podium', 'dl-9', [
    'Podium auf Beschädigungen / Korrosion',
    'Beklebung / Warnmarkierungen / Hinweisschilder',
    'Safetywalk / Sprossen- und Kantenschutz',
    'Podiumsdeckfläche',
    'Befestigungsschrauben',
    'Zusatzklappen / Verschlüsse / Wartungsöffnungen'
  ]),
  createCheckSection('sec-dl-10', '10. Fahrzeug von unten', 'dl-10', [
    'Hydraulikpumpe / Dichtheit / Befestigung',
    'Kardanwelle',
    'Flansche',
    'Fahrzeugrahmen',
    'Hilfsrahmen',
    'Schweissnähte',
    'Elektrische Drehdurchführung',
    'Verschraubungen Fahrzeugrahmen',
    'Spritzlappen Energiezuführung Abstützung',
    'Spritzschutzwinkel Abstützträger',
    'Ölkühler'
  ]),
  createCheckSection('sec-dl-11', '11. Drehgestell', 'dl-11', [
    'Drehkranzschrauben',
    'Verkleidungen / Bleche / Designverkleidungen',
    'Wasserabweiser Drehgestellabdeckung',
    'Grundplatte / Drehgestell / Halterungen / Rahmen Arbeitsplattform',
    'Hydraulikanlage',
    'Drehgetriebe',
    'Elektrische Bauteile',
    'Sicherungskästen / Schaltkästen / Verteilerdosen'
  ]),
  createCheckSection('sec-dl-12', '12. Lafette', 'dl-12', [
    'Dehnschrauben Leitersatz',
    'Lastmessbolzen',
    'Dynamometerbolzen',
    'Segmentbogen',
    'Messingführungsschienen',
    'Aufrichteachse'
  ]),
  createCheckSection('sec-dl-13', '13. HBST', 'dl-13', [
    'Sitz / Sitzschale / Armlehne / RÜckenlehne / Wetterschutzdach',
    'Beklebung / Beschilderung',
    'Spritzschutzwinkel PLC 2',
    'Bedienelemente HBST',
    'ABA',
    'Fahrbewegungen / Leiterablage / TMS / VRS / ARF',
    'Geometrische / Lastgrenzen',
    'Baugruppen Notbetrieb',
    'Gradbogen',
    'Beleuchtung HBST',
    'Sprechanlage',
    'Fusstaster',
    'Verstellung Scheinwerfer Unterleiter'
  ]),
  createCheckSection('sec-dl-14', '14. Generatorplattform', 'dl-14', [
    'Generatorplattform',
    'Generator',
    '230 / 400 Volt Anlage',
    'Atemluftanlage',
    'Halte- und Umlenkpunkte Absturzsicherung'
  ]),
  SPEED_CHECK_SECTION,
  createCheckSection('sec-dl-15', '15. Leitersatz', 'dl-15', [
    'Leiterauflage',
    'Kunstschienen / Messingplatten',
    'Designbleche / Schutzgitter / Eingreifschutz',
    'Halterungen Leitersatz',
    'Beklebung / Beschilderung',
    'Leiterteile / Sprossen / K-Verbände',
    'Ober- und Untergurt',
    'Sprossenbeläge',
    'Drahtseile Spannung',
    'Drahtseile Zustand',
    'Umlenkrollen Drahtseile',
    'Kopfrollen / FÜhrungsrollen',
    'Messingführungen / Kunststoffgleitklötze',
    'Ausschubzylinder',
    'Leitersatzverriegelung',
    'Hauptsteuerkabel / 400V-Kabel / Neigekabel',
    'Klemmdosen',
    'Atemluftanlage Leitersatz',
    'Hydrauliksystem Korbsteuerung',
    'Wasserabweiser Gelenkarmzylinder',
    'Lastösen',
    'Kabel / Kabelführungen',
    'Sensoren',
    'Oberleiterkasten',
    'Panzersteckrohre',
    'Kranwinde',
    'Lift',
    'Korbgabel / Korbaufnahme / Korbsegment',
    'Korbverriegelung',
    'Verbindungen Leiterspitze / Korb',
    'Korbwinkelgeber',
    'Schubstange / Drahtseile / E-Antrieb Korbnivellierung'
  ]),
  createCheckSection('sec-dl-16', '16. Korb', 'dl-16', [
    'Korb Mechanik',
    'Freigabetaster',
    '230 / 400 Volt Anlage',
    'Wasserverrohrung',
    'Multifunktionssäule / Verriegelungen / Markierungen',
    'Beleuchtung Korb',
    'Korbdisplay / Bedienelemente',
    'Funktionen Bedienstand Korb',
    'Sprechanlage',
    'Hydraulische Anlage Korb',
    'Gerätekasten Korb',
    'Sprühdüsen / Selbstschutzeinrichtungen',
    'Beklebung / Beschilderung',
    'Windmesser',
    'Anschlag- / RÜckhaltepunkte',
    'Fallschutzsystem',
    'Hochspannungswarneinrichtung'
  ]),
  createCheckSection('sec-dl-17', '17. Anbauteile', 'dl-17', [
    'SKL',
    'Aufstiegsleiter',
    'Einhängevorrichtung / Rollglisshalter',
    'Monitor',
    'Verbindungsschlauch Monitor',
    'Multifunktionshalter',
    'Zusätzlicher Handlauf',
    'Multifunktionslagerung',
    'LÜfterhalterung',
    'Kaminfegerwerkzeug',
    'Steckzapfen',
    'Rollstuhlrampe',
    'Schuttmulde',
    'Verbreiterung Schwerlast SKL',
    'Taucherleiter',
    'Halter Powermoon',
    'Aufstecklagerung Scheinwerfer'
  ]),
  createCheckSection('sec-dl-18', '18. Allgemein', 'dl-18', [
    'Überlastsicherung / Lasthupe',
    'Überlastprüfung / Hysterese',
    'Sicherheitseinrichtungen',
    'Filtereinsatz Haupthydraulik',
    'Eintrag Prüfbuch'
  ]),
  {
    id: 'sec-operational-status-1',
    title: '19. Einsatzfähigkeit',
    total: 1,
    completed: 0,
    items: [],
    customStateKey: 'operational-status'
  }
];
