import type { CheckSectionModel } from '@features/sections/check-section/check-section';
import { createCheckSection } from '../../build/section-factories';
import { createBatteryCheckSection, SPEED_CHECK_SECTION } from '../shared.sections';

export const DREHLEITER_UVV_BASE_SECTIONS: CheckSectionModel[] = [
  createCheckSection('sec-dl-1', '1. Fahrerhaus innen', 'dl-1', [
    'Gangsperre',
    'Nebenantrieb-Kontrollleuchte',
    'Kontrollleuchten Achsverriegelung / Sitz / Korb',
    'Kontrollleuchten Fahrerhaus',
    'Warnsummer Grundstellung / Geraeteraum',
    'Verriegelung / Notbetaetigung PA',
    'Ladeerhaltung',
    'Durchsageanlage',
    'Batteriehauptschalter',
    'Rueckfahrkamerasystem',
    'Lagerung / Sicherung Gegenstaende',
    'Beschilderung Masse / Gewichte'
  ]),
  createCheckSection('sec-dl-2', '2. Fahrerhaus aussen', 'dl-2', [
    'Akustische Warneinrichtung',
    'Beleuchtung Chassis / Aufbau',
    'Abdeckkappen Ladeerhaltung',
    'Beschilderung Fahrerhaus',
    'Schaekel (Splint / Beschilderung)'
  ]),
  createCheckSection('sec-dl-3', '3. Fahrzeugaufbau', 'dl-3', [
    'Fahrzeug auf Unfallschaeden',
    'Kraftstoffbehaelter',
    'Einfuellstutzen',
    'Tankdeckel',
    'Tankklappe',
    'AdBlue-Behaelter',
    'Radkeile inkl. Halter und Verriegelung',
    'Oelstand Haupthydraulik'
  ]),
  createBatteryCheckSection('4. Batterien'),
  createCheckSection('sec-dl-5', '5. Geraetekaesten', 'dl-5', [
    'Geraetekaesten',
    'Ueberwachungseinrichtung',
    'Beleuchtung',
    'Festigkeit der Anbauteile'
  ]),
  createCheckSection('sec-dl-6', '6. Aufstiege', 'dl-6', ['Aufstiege', 'Aufstiegsleitern']),
  createCheckSection('sec-dl-7', '7. Abstuetzung', 'dl-7', [
    'Beleuchtungen / Funktionen / Befestigungen / Dichtheit',
    'Abstuetzung',
    'Abstutzbedienpulte',
    'Hydraulik Unterwagen',
    'Ueberwachung (Sensorik)',
    'Bodenkontaktmechanik',
    'Abstuetzbalken / Stuetztraeger',
    'Schweissnaehte Abstuetztraeger',
    'Schmierstellen Unterwagen',
    'Wartungsdeckel Abstuetztraeger',
    'Energiezufuehrungen / Oelharfen',
    'Achsverriegelung'
  ]),
  createCheckSection('sec-dl-8', '8. Notbetriebseinrichtungen', 'dl-8', [
    'Notbetriebseinrichtungen Unterwagen',
    'Notbetriebspumpen / Notbetriebsmotor',
    'Ventile Notbetrieb Abstuetzung',
    'Umschaltvorrichtung Energiefreigabe Korbmotoren',
    'Umschaltventil Unterwagen / Oberwagen'
  ]),
  createCheckSection('sec-dl-9', '9. Podium', 'dl-9', [
    'Podium auf Beschaedigungen / Korrosion',
    'Beklebung / Warnmarkierungen / Hinweisschilder',
    'Safetywalk / Sprossen- und Kantenschutz',
    'Podiumsdeckflaeche',
    'Befestigungsschrauben',
    'Zusatzklappen / Verschluesse / Wartungsoeffnungen'
  ]),
  createCheckSection('sec-dl-10', '10. Fahrzeug von unten', 'dl-10', [
    'Hydraulikpumpe / Dichtheit / Befestigung',
    'Kardanwelle',
    'Flansche',
    'Fahrzeugrahmen',
    'Hilfsrahmen',
    'Schweissnaehte',
    'Elektrische Drehdurchfuehrung',
    'Verschraubungen Fahrzeugrahmen',
    'Spritzlappen Energiezufuehrung Abstuetzung',
    'Spritzschutzwinkel Abstuetztraeger',
    'Oelkuehler'
  ]),
  createCheckSection('sec-dl-11', '11. Drehgestell', 'dl-11', [
    'Drehkranzschrauben',
    'Verkleidungen / Bleche / Designverkleidungen',
    'Wasserabweiser Drehgestellabdeckung',
    'Grundplatte / Drehgestell / Halterungen / Rahmen Arbeitsplattform',
    'Hydraulikanlage',
    'Drehgetriebe',
    'Elektrische Bauteile',
    'Sicherungskaesten / Schaltkaesten / Verteilerdosen'
  ]),
  createCheckSection('sec-dl-12', '12. Lafette', 'dl-12', [
    'Dehnschrauben Leitersatz',
    'Lastmessbolzen',
    'Dynamometerbolzen',
    'Segmentbogen',
    'Messingfuehrungsschienen',
    'Aufrichteachse'
  ]),
  createCheckSection('sec-dl-13', '13. HBST', 'dl-13', [
    'Sitz / Sitzschale / Armlehne / Rueckenlehne / Wetterschutzdach',
    'Beklebung / Beschilderung',
    'Spritzschutzwinkel PLC 2',
    'Bedienelemente HBST',
    'ABA',
    'Fahrbewegungen / Leiterablage / TMS / VRS / ARF',
    'Geometrische / Lastgrenzen',
    'Baugruppen Notbetrieb',
    'Gradbogen',
    'Beleuchtung HBST',
    'Sprechanlage',
    'Fusstaster',
    'Verstellung Scheinwerfer Unterleiter'
  ]),
  createCheckSection('sec-dl-14', '14. Generatorplattform', 'dl-14', [
    'Generatorplattform',
    'Generator',
    '230 / 400 Volt Anlage',
    'Atemluftanlage',
    'Halte- und Umlenkpunkte Absturzsicherung'
  ]),
  SPEED_CHECK_SECTION,
  createCheckSection('sec-dl-15', '15. Leitersatz', 'dl-15', [
    'Leiterauflage',
    'Kunstschienen / Messingplatten',
    'Designbleche / Schutzgitter / Eingreifschutz',
    'Halterungen Leitersatz',
    'Beklebung / Beschilderung',
    'Leiterteile / Sprossen / K-Verbaende',
    'Ober- und Untergurt',
    'Sprossenbelaege',
    'Drahtseile Spannung',
    'Drahtseile Zustand',
    'Umlenkrollen Drahtseile',
    'Kopfrollen / Fuehrungsrollen',
    'Messingfuehrungen / Kunststoffgleitkloetze',
    'Ausschubzylinder',
    'Leitersatzverriegelung',
    'Hauptsteuerkabel / 400V-Kabel / Neigekabel',
    'Klemmdosen',
    'Atemluftanlage Leitersatz',
    'Hydrauliksystem Korbsteuerung',
    'Wasserabweiser Gelenkarmzylinder',
    'Lastoesen',
    'Kabel / Kabelfuehrungen',
    'Sensoren',
    'Oberleiterkasten',
    'Panzersteckrohre',
    'Kranwinde',
    'Lift',
    'Korbgabel / Korbaufnahme / Korbsegment',
    'Korbverriegelung',
    'Verbindungen Leiterspitze / Korb',
    'Korbwinkelgeber',
    'Schubstange / Drahtseile / E-Antrieb Korbnivellierung'
  ]),
  createCheckSection('sec-dl-16', '16. Korb', 'dl-16', [
    'Korb Mechanik',
    'Freigabetaster',
    '230 / 400 Volt Anlage',
    'Wasserverrohrung',
    'Multifunktionssaeule / Verriegelungen / Markierungen',
    'Beleuchtung Korb',
    'Korbdisplay / Bedienelemente',
    'Funktionen Bedienstand Korb',
    'Sprechanlage',
    'Hydraulische Anlage Korb',
    'Geraetekasten Korb',
    'Spruehduesen / Selbstschutzeinrichtungen',
    'Beklebung / Beschilderung',
    'Windmesser',
    'Anschlag- / Rueckhaltepunkte',
    'Fallschutzsystem',
    'Hochspannungswarneinrichtung'
  ]),
  createCheckSection('sec-dl-17', '17. Anbauteile', 'dl-17', [
    'SKL',
    'Aufstiegsleiter',
    'Einhaengevorrichtung / Rollglisshalter',
    'Monitor',
    'Verbindungsschlauch Monitor',
    'Multifunktionshalter',
    'Zusaetzlicher Handlauf',
    'Multifunktionslagerung',
    'Luefterhalterung',
    'Kaminfegerwerkzeug',
    'Steckzapfen',
    'Rollstuhlrampe',
    'Schuttmulde',
    'Verbreiterung Schwerlast SKL',
    'Taucherleiter',
    'Halter Powermoon',
    'Aufstecklagerung Scheinwerfer'
  ]),
  createCheckSection('sec-dl-18', '18. Allgemein', 'dl-18', [
    'Ueberlastsicherung / Lasthupe',
    'Ueberlastpruefung / Hysterese',
    'Sicherheitseinrichtungen',
    'Filtereinsatz Haupthydraulik',
    'Eintrag Pruefbuch'
  ]),
  {
    id: 'sec-operational-status-1',
    title: '19. Einsatzfaehigkeit',
    total: 1,
    completed: 0,
    items: [],
    customStateKey: 'operational-status'
  }
];
