import type { CheckSectionModel } from '@features/sections/check-section/check-section';
import { createCheckSection } from '../../build/section-factories';
import { BATTERY_CHECK_SECTION, SPEED_CHECK_SECTION } from '../shared.sections';

export const DREHLEITER_UVV_BASE_SECTIONS: CheckSectionModel[] = [
  createCheckSection('sec-dl-1', 'Fahrerhaus Innen', 'dl-1', [
    'Gangsperre',
    'Nebenantrieb Kontrollleuchte',
    'Kontrollleuchte Achsverriegelung, Sitz, Korb',
    'Kontrollleuchte fuer saemtliche Funktionen im Fahrerhaus pruefen, soweit moeglich',
    'Warnsummer fuer Fahrzeug nicht in Grundstellung / Geraeteraum geoeffnet auf Funktion pruefen',
    'Verriegelung / Notbetaetigung PA',
    'Ladeerhaltung (Handscheinwerfer, Funk...)',
    'Durchsageanlage',
    'Batteriehauptschalter',
    'Rueckfahrkamerasystem',
    'Lagerung / Sicherung sonstiger Gegenstaende',
    'Beschilderung Fahrzeugmasse / Gewichte'
  ]),
  createCheckSection('sec-dl-2', 'Fahrerhaus Aussen', 'dl-2', [
    'Akustische Warneinrichtung',
    'Beleuchtungseinrichtungen am Gesamtfahrzeug (Chassis + Aufbau)',
    'Abdeckkappen Ladeerhaltung',
    'Beschilderung am Fahrerhaus',
    'Schaekel (Funktion, Splint, Beschilderung)'
  ]),
  createCheckSection('sec-dl-3', 'Fahrzeugaufbau und Geraeteraeume', 'dl-3', [
    'Fahrzeug auf Unfallschaeden pruefen',
    'Kraftstoffbehaelter, Einfuellstutzen, Tankdeckel und Tankklappe auf Dichtheit und Funktion pruefen',
    'AdBlue-Behaelter auf Dichtheit, Befestigung und Funktion pruefen',
    'Batterie / Batteriefach inkl. Spannung, Alter, Fluessigkeitsstand, Korrosion der Pole und Saeuredichte pruefen',
    'Batterietest mit Ausdruck durchfuehren',
    'Abdeckung und Verriegelung pruefen',
    'Auszug, Wanne (VA), Kabelfuehrung, Kabelsicherung und Entlueftung pruefen',
    'Batteriehalter (Befestigung) Sichtpruefung durchfuehren',
    'Geraetekaesten auf Beschaedigungen, Ueberwachungseinrichtung, Beleuchtung und Festigkeit der Anbauteile pruefen',
    'Aufstiege auf Befestigung, Beleuchtung und allgemeinen Zustand pruefen',
    'Unterlegplatten, Radkeile inkl. Halter und Verriegelung auf Beschaedigung und Funktion pruefen',
    'Aufstiegsleitern inkl. Verriegelung, Ueberwachung, Sprossen und Griffe pruefen',
    'Oelstand Haupthydraulik pruefen'
  ]),
  BATTERY_CHECK_SECTION,
  createCheckSection('sec-dl-4', 'Achsverriegelung, Abstuetzung und Notbetriebseinrichtungen', 'dl-4', [
    'Beleuchtungen, Funktionen, Befestigungen und Dichtheit pruefen',
    'Abstuetzung Sicht- und Funktionskontrolle (hydraulisch)',
    'Abstuetzbedienpulte Sicht- und Funktionskontrolle',
    'Hydraulische Komponenten im Unterwagen auf Dichtheit und Zustand pruefen',
    'Ueberwachung (Sensorik) sowie Kabel, Anschlussstecker und Anschlussdose pruefen',
    'Bodenkontaktmechanik auf Beschaedigung und Korrosion pruefen',
    'Abstuetzbalken / Stuetztraeger pruefen',
    'Schweissnaehte der Abstuetztraeger auf Risse pruefen',
    'Schmierzustand aller Schmierstellen im Unterwagen pruefen',
    'Wartungsdeckel der Abstuetztraeger oeffnen und Sichtkontrolle durchfuehren',
    'Energiezufuehrungen und Oelharfen auf Zustand pruefen',
    'Achsverriegelung auf Zustand, Freigaengigkeit, Funktion, Dichtheit und Einstellung pruefen',
    'Notbetriebseinrichtungen Unterwagen pruefen',
    'Notbetriebspumpen bzw. Notbetriebsmotor Sicht- und Funktionspruefung',
    'Ventile Notbetrieb Abstuetzung Sicht- und Funktionspruefung',
    'Umschaltvorrichtung Energiefreigabe Korbmotoren Sicht- und Funktionspruefung',
    'Betaetigung Umschaltventil Unterwagen / Oberwagen Sicht- und Funktionspruefung'
  ]),
  createCheckSection('sec-dl-5', 'Podium', 'dl-5', [
    'Podium vollstaendig auf Beschaedigungen und Korrosion pruefen',
    'Beklebung, Warnmarkierungen, Hinweisschilder, Safetywalk, Sprossen- und Kantenschutz pruefen',
    'Podiumsdeckflaeche auf Beschaedigung, Verunreinigung und Vollstaendigkeit der Befestigungsschrauben pruefen',
    'Zusatzklappen, Verschluesse und Wartungsoeffnungen auf Funktion und Beschaedigung pruefen'
  ]),
  createCheckSection('sec-dl-6', 'Fahrzeug von unten', 'dl-6', [
    'Hydraulikpumpe und deren Antrieb Sichtpruefung durchfuehren',
    'Fahrzeugrahmen, Hilfsrahmen, Podium und Geraetekaesten Sichtpruefung durchfuehren',
    'Elektrische Drehdurchfuehrung Sichtpruefung durchfuehren',
    'Verschraubungen zum Fahrzeugrahmen Sichtpruefung durchfuehren',
    'Zusaetzliche Spritzlappen an der Energiezufuehrung der Abstuetzung pruefen',
    'Spritzschutzwinkel an den Abstuetztraegern pruefen',
    'Oelkuehler Sichtpruefung durchfuehren'
  ]),
  createCheckSection('sec-dl-7', 'Drehgestell, Lafette, HBST und Generatorplattform', 'dl-7', [
    'Drehkranzschrauben auf festen Sitz und Vollstaendigkeit pruefen',
    'Verkleidungen, Bleche und Designverkleidungen auf Beschaedigung und Vollstaendigkeit pruefen',
    'Zusaetzlichen Wasserabweiser obere Drehgestellabdeckung pruefen',
    'Grundplatte, Drehgestell, Lafette, Halterungen und Rahmen HBST/Arbeitsplattform auf Schweissnaehte, Korrosion und Beschaedigungen pruefen',
    'Hydraulikanlage Sichtpruefung (Zustand und Dichtheit)',
    'Drehgetriebe Sichtpruefung',
    'Elektrische Bauteile Sichtpruefung',
    'Sicherungskaesten, Schaltkaesten und Verteilerdosen auf Korrosion und Dichtheit kontrollieren',
    'Sitz, Sitzschale, Armlehne, Rueckenlehne und Wetterschutzdach pruefen',
    'Beklebung und Beschilderung auf Beschaedigung und Vollstaendigkeit pruefen',
    'Spritzschutzwinkel PLC 2 pruefen',
    'Alle Bedienelemente des HBST auf Zustand und Funktion pruefen',
    'ABA Sicht- und Funktionspruefung',
    'Alle Fahrbewegungen inkl. automatische Leiterablage, TMS, VRS, ARF usw. pruefen',
    'Geometrische und Lastgrenzen pruefen',
    'Alle Baugruppen des Notbetriebes auf Zustand und Funktion pruefen',
    'Gradbogen Sichtpruefung',
    'Alle Beleuchtungseinrichtungen des HBST auf Zustand und Funktion pruefen',
    'Sprechanlage auf Zustand und Funktion pruefen',
    'Fusstaster auf Zustand und Funktion pruefen',
    'Verstellung Scheinwerfer Unterleiter pruefen',
    'Dehnschrauben Leitersatz Sichtpruefung',
    'Lastmessbolzen Sichtpruefung',
    'Dynamometerbolzen Sichtpruefung',
    'Segmentbogen Sichtpruefung',
    'Messingfuehrungsschienen Sichtpruefung',
    'Aufrichteachse Sichtpruefung',
    'Generatorplattform Sichtpruefung',
    'Generator Sicht- und Funktionspruefung',
    'Alle Bauteile der 230 / 400 Volt Anlage Sicht- und Funktionspruefung',
    'Atemluftanlage Sichtpruefung',
    'Halte- und Umlenkpunkte Absturzsicherung Sichtpruefung'
  ]),
  createCheckSection('sec-dl-8', 'Leitersatz', 'dl-8', [
    'Sichtpruefung der Leiterauflage',
    'Leiterauflage auf Kunstschienen / Entfernung der Messingplatten pruefen',
    'Designbleche, Schutzgitter und Eingreifschutz Sichtpruefung',
    'Halterungen am Leitersatz Sicht- und Funktionskontrolle',
    'Beklebung und Beschilderung auf Beschaedigung und Vollstaendigkeit pruefen',
    'Leiterteile, Sprossen, K-Verbaende sowie Ober- und Untergurt Sichtpruefung',
    'Sprossenbelaege Zustand pruefen',
    'Spannung der Drahtseile im Leitersatz kontrollieren',
    'Zustand der Drahtseile ueberpruefen',
    'Umlenkrollen der Drahtseile Sichtpruefung',
    'Kopfrollen, seitliche Fuehrungsrollen, Messingfuehrungen und Kunststoffgleitkloetze Sichtpruefung',
    'Ausschubzylinder Sichtpruefung',
    'Leitersatzverriegelung Sichtpruefung',
    'Hauptsteuer-, 400V- und Neigekabel auf Beschaedigung, Schmierung, Drall, Spannung und Abnutzung pruefen',
    'Klemmdosen auf Beschaedigungen, Wassereintritt und korrekte Einbaulage pruefen',
    'Atemluftanlage im Leitersatz Sichtpruefung',
    'Hydrauliksystem der Korbsteuerung Sichtpruefung',
    'Zusaetzlichen Abweiser fuer Wasserfuehrung an den Gelenkarmzylindern pruefen',
    'Lastoesen Sichtpruefung',
    'Kabel und Kabelfuehrungen Sichtpruefung',
    'Sensoren auf Beschaedigungen pruefen',
    'Oberleiterkasten Sichtpruefung',
    'Panzersteckrohre im Leitersatz auf Vollstaendigkeit und Beschaedigung pruefen',
    'Kranwinde Sicht- und Funktionspruefung',
    'Lift Sicht- und Funktionspruefung'
  ]),
  createCheckSection('sec-dl-9', 'Korb', 'dl-9', [
    'Korbgabel, Korbaufnahme und Korbsegment Sichtpruefung',
    'Korbverriegelung Funktion und Sichtpruefung',
    'Verbindungen hydraulisch und elektrisch zwischen Leiterspitze und Korb pruefen',
    'Korbwinkelgeber Sichtpruefung',
    'Kontrolle Schubstange, Drahtseile und E-Antrieb Korbnivellierung',
    'Korb auf Beschaedigungen, Verformungen, Abnutzungen und Funktionen der Mechanik pruefen',
    'Freigabetaster Sicht- und Funktionskontrolle',
    '230 / 400 Volt Anlage im Korb Sichtpruefung',
    'Wasserverrohrung Sichtpruefung',
    'Multifunktionssaeule, Verriegelungen und Markierungen Sichtpruefung',
    'Alle Beleuchtungseinrichtungen auf Funktion und Beschaedigung pruefen',
    'Korbdisplay, Bedienoberflaeche, Taster, Schalter, Joysticks und Drehpotentiometer pruefen',
    'Alle Funktionen des Bedienstands Korb testen',
    'Sprechanlage Funktionstest mit und ohne Korbstecker',
    'Hydraulische Anlage Korb Sichtpruefung',
    'Geraetekasten im Korb Sicht- und Funktionspruefung',
    'Spruehduesen (Selbstschutzeinrichtungen) Sichtpruefung',
    'Beklebung und Beschilderung auf Beschaedigungen und Vollstaendigkeit pruefen',
    'Windmesser Funktion pruefen',
    'Anschlag- und Rueckhaltepunkte auf Verformung und Beschaedigung pruefen',
    'Fallschutzsystem Sichtpruefung',
    'Hochspannungswarneinrichtung Sichtpruefung'
  ]),
  createCheckSection('sec-dl-10', 'Anbauteile', 'dl-10', [
    'SKL Sicht- und Funktionskontrolle',
    'Aufstiegsleiter Sicht- und Funktionskontrolle',
    'Einhaengevorrichtung (Rollglisshalter) Sicht- und Funktionskontrolle',
    'Monitor Sicht- und Funktionskontrolle',
    'Verbindungsschlauch fuer Monitor Leiterspitze-Korb Sichtpruefung',
    'Sonstige Halter und Geraete Sicht- und Funktionspruefung'
  ]),
  createCheckSection('sec-dl-11', 'Allgemein', 'dl-11', [
    'Pruefung Ueberlastsicherung (Lasthupe)',
    'Ueberlastpruefung (Hysterese), Messwert in mm dokumentieren',
    'Ueberpruefung der Sicherheitseinrichtungen',
    'Wechseln des Filtereinsatzes der Haupthydraulikanlage',
    'Eintrag ins Pruefbuch der Drehleiter',
    'Maengel dokumentieren'
  ]),
  SPEED_CHECK_SECTION
];
